name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            target

      - name: Install cargo-binstall
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall

      - name: Add Cargo Third-Party Tools
        run: |
          if ! command -v cargo-audit &> /dev/null; then
            cargo binstall cargo-audit --no-confirm
          fi

          if ! command -v cargo-tarpaulin &> /dev/null; then
            cargo binstall cargo-tarpaulin --no-confirm
          fi
      - name: Check documentation
        run: cargo doc --no-deps --document-private-items

      - name: Security audit
        run: cargo audit

      - name: Run Rustfmt
        run: cargo fmt --all -- --check

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build
        run: cargo build --all-features --verbose

      - name: Run tests
        run: cargo tarpaulin --all-features --verbose --out Xml --output-dir target/tarpaulin

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: target/tarpaulin/cobertura.xml
          token: ${{ secrets.CODECOV_TOKEN }}
