name: GitHub Pages Build and Deploy

permissions:
  contents: write
  pages: write

on:
  workflow_dispatch:
  push:
    branches:
      - gh-pages-source

concurrency:
  group: gh-pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Build static site
        run: node scripts/build.mjs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: gh-pages-source
